on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
        default: |
          GITHUB_SHA=${{ github.sha }}
      runs-on:
        type: string
        required: false
        default: "ubuntu-latest"
        
permissions:
  contents: read
  packages: write
            
jobs:
  build:
    name: "Docker Build"
    runs-on: ${{ inputs['runs-on'] }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Build Cache Key
        id: cachekey
        run: |
            BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||')
            BRANCH_HASH=$(echo -n "$BRANCH_NAME" | sha1sum | awk '{print $1}')
            echo "CACHE_KEY=branch-$BRANCH_HASH" >> $GITHUB_ENV
            echo $CACHE_KEY

      - name: Build & push with build args
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ env.CACHE_KEY }}
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ env.CACHE_KEY }},mode=max
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          build-args: ${{ inputs.build-args }}

      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json

      - name: Scan image with Grype
        uses: anchore/scan-action@v4
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          fail-build: false          
          severity-cutoff: medium