on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
        default: |
          GITHUB_SHA=${{ github.sha }}
      runs-on:
        type: string
        required: false
        default: "ubuntu-latest"
      continue-on-security-error:
        description: "Continue on security check errors"
        required: false
        type: boolean
        default: false
        
permissions:
  contents: read
  packages: write
            
jobs:
  build:
    name: "Docker Build"
    runs-on: ${{ inputs['runs-on'] }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Build Cache Key
        id: cachekey
        run: |
            BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||')
            BRANCH_HASH=$(echo -n "$BRANCH_NAME" | sha1sum | awk '{print $1}')
            echo "CACHE_KEY=branch-$BRANCH_HASH" >> $GITHUB_ENV
            echo $CACHE_KEY

      - name: Build & push with build args
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ env.CACHE_KEY }}
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ env.CACHE_KEY }},mode=max
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          build-args: ${{ inputs.build-args }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Cache Grype DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/grype/
          key: grype-db-${{ runner.os }}-v1

      - name: Scan image with Grype
        id: scan
        uses: anchore/scan-action@v7
        with:
          fail-build: true
          severity-cutoff: medium
          output-format: sarif
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
        continue-on-error: ${{ inputs.continue-on-security-error }}

      - name: Inspect action SARIF report
        if: always()  
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Annotate SARIF findings
        if: always()
        run: |
          jq -r '
            .runs[].results[] |
            "::error file=\(.locations[0].physicalLocation.artifactLocation.uri)," +
            "line=\(.locations[0].physicalLocation.region.startLine)//0" +
            "::[\(.ruleId)] \(.message.text)"
          ' ${{ steps.scan.outputs.sarif }} || true

      - name: Summarize SARIF findings
        if: failure()
        run: |
          echo "### Vulnerability Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Rule | Severity | File | Message |" >> $GITHUB_STEP_SUMMARY
          echo "|------|----------|------|---------|" >> $GITHUB_STEP_SUMMARY
          SEVERITY_CUTOFF="medium"
          jq -r --arg cutoff "$SEVERITY_CUTOFF" '
            .runs[].results[]
            | select(.properties.severity | IN("medium","high","critical"))
            | "| \(.ruleId) | \(.properties.severity // "n/a") | \(.locations[0].physicalLocation.artifactLocation.uri) | \(.message.text) |"
          ' ${{ steps.scan.outputs.sarif }} >> $GITHUB_STEP_SUMMARY || true

      - name: Upload SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sarif-report
          path: ${{ steps.scan.outputs.sarif }}