on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
        default: |
          BUILDKIT_INLINE_CACHE=1
          DOCKER_BUILDKIT=1
          GITHUB_SHA=${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}
          restore-keys: ${{ runner.os }}-buildx-main

      - name: Build Docker Image
        run: |
          # Split the build-args string into an array (newline-separated)
          IFS=$'\n' read -r -a build_args_array <<< "${{ inputs.build-args }}"

          # Construct the --build-arg options
          build_arg_options=""
          for arg in "${build_args_array[@]}"; do
            build_arg_options+="--build-arg $arg "
          done

          # Execute the Docker build command
          docker buildx build \
            --file Dockerfile \
            --tag ${{ github.repository }}:${{ github.sha }} \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            $build_arg_options \
            --load .