on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
        default: |
          BUILDKIT_INLINE_CACHE=1
          DOCKER_BUILDKIT=1
          GITHUB_SHA=${{ github.sha }}

permissions:
  contents: read
  packages: write
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push with build args
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build-args }}
