on:
  workflow_call:
    inputs:
      account-id:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: "us-east-1"


permissions:
  id-token: write
  contents: read
  packages: read

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/prod' && 'prod' || (github.ref == 'refs/heads/main' && 'sandbox' || 'sandbox')) }}
  ECR_REPOSITORY_URI: "${{ inputs.account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.repository.name }}"

jobs:
  tag_image:
    name: Tag Docker Image
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/cicd-changes'))
    environment: >-
      ${{
        github.event.inputs.environment ||
        (github.ref == 'refs/heads/prod' && 'prod' || (github.ref == 'refs/heads/main' && 'sandbox' || 'sandbox'))
      }}
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: "${{ github.event.repository.name }}-TagImage-${{ env.ENVIRONMENT }}"
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries:  ${{ inputs.account-id }}

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Tag and Push Docker image to ECR
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ${{ env.ECR_REPOSITORY_URI }}:${{ env.ENVIRONMENT }}
          docker push ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ env.ECR_REPOSITORY_URI }}:${{ env.ENVIRONMENT }}
          echo "Tagged and pushed for environment: ${{ env.ENVIRONMENT }}"
