on:
  workflow_call:
    inputs:
      contract-directory:
        type: string
        required: false
        default: contracts
        description: the root folder for contracts
      run-integration-tests:
        type: boolean
        required: false
        default: true
        description: whether to run integration tests
      env-vars:
        description: 'Multiline list of KEY=VALUE pairs to set in the environment'
        required: false
        default: ''
        type: string
          
jobs:
  check:
    name: "Solidity Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set dynamic environment variables
        if: ${{ inputs['env-vars'] != '' }}
        shell: bash
        run: |
          echo "${{ inputs['env-vars'] }}" | sed '/^\s*$/d' >> $GITHUB_ENV

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Run Contracts Unit Tests
        run: |
          echo "INFO: Running Solidity tests..."
          cd ${{inputs.contract-directory}}
          forge test -vvv --mc Unit
        
      - name: Run Contracts Linting
        run: |
          echo "INFO: Checking Solidity formatting..."
          cd ${{inputs.contract-directory}}
          forge fmt --check
        
      - name: Run Contracts Integration Tests
        if: ${{ inputs.run-integration-tests == true }}
        run: |
          echo "INFO: Running Solidity integration tests..."
          cd ${{inputs.contract-directory}}
          forge test -vvv --mc Integration
    
